### ISSUE TITLE
Building Example App

### ISSUE THREAD

**Issue by rmurphy2718** [dccspeed/fractal#9]
Dear Fractal,

I am trying to run your example of putting a custom app inside fractal_apps.  I am getting an error and I think it may have to do with pointing `gradlew` to the correct spark master.  I am attaching a log and a screenshot of my project structure and code.  Are you able to find what's going wrong?  Thanks so much.

[Building_App_First.log](https://github.com/dccspeed/fractal/files/3614262/Building_App_First.log)
![image](https://user-images.githubusercontent.com/15987518/64927554-4a3f1000-d7da-11e9-8cad-e83856b2d286.png)

**Comment by viniciusvdias** [comment]
The good news is that your app is built, the assemble returned success. Also, the error I see in this log is unrelated to your application, it happens during unit tests.

The bad news is that this may be an unexpected race condition. Is this happening every time you try to build your project?

**Comment by rmurphy2718** [comment]
In fact, I just ran it twice more and I didn't get any errors.  Since yesterday, I know I closed my spark master and worker, and I just relaunched them.

What do these security warnings mean?  About serialization?

I will go ahead and try to run your app now, with the successful build.

**Comment by viniciusvdias** [comment]
Yes, seems like there is a race condition. I will try to debug this, but I think this will not interfere with your purposes.

About the warning, this is because of the framework we use for communication: Akka. Basically it is saying that this implementation is using the default java serialization for messages, which is known to be sub-optimal. Since we do not implement a custom optimized serialized for those messages, akka makes sure to point that out :)
